### PR TITLE
Update OpenCensus, gRPC and Prometheus version

### PR DESCRIPTION
**Pull request by songy23**
To access the SNAPSHOT release, please add the following lines to ~/.m2/settings.xml: 

```
<profiles>
  <profile>
     <id>allow-snapshots</id>
        <activation><activeByDefault>true</activeByDefault></activation>
     <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
   </profile>
</profiles>
```

### CODE REVIEW

**Comment by odeke-em** [comment]
Thank you @songy23 for working on this!

I just tried it but unfortunately I get back this build failure resulting from conflicting dependencies. 
```shell
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.356 s
[INFO] Finished at: 2018-05-30T11:45:18-07:00
[INFO] Final Memory: 14M/47M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ocgrpc: Could not resolve dependencies for project io.ocgrpc:ocgrpc:jar:1.0-SNAPSHOT: Failed to collect dependencies for io.ocgrpc:ocgrpc:jar:1.0-SNAPSHOT: Could not resolve version conflict among [io.grpc:grpc-netty:jar:1.9.0 -> io.grpc:grpc-core:jar:[1.9.0,1.9.0], io.grpc:grpc-protobuf:jar:1.9.0 -> io.grpc:grpc-core:jar:1.9.0, io.grpc:grpc-protobuf:jar:1.9.0 -> io.grpc:grpc-protobuf-lite:jar:1.9.0 -> io.grpc:grpc-core:jar:1.9.0, io.grpc:grpc-stub:jar:1.9.0 -> io.grpc:grpc-core:jar:1.9.0, io.opencensus:opencensus-exporter-stats-stackdriver:jar:0.14.0-SNAPSHOT -> com.google.cloud:google-cloud-monitoring:jar:0.47.0-beta -> io.grpc:grpc-netty-shaded:jar:1.10.1 -> io.grpc:grpc-core:jar:[1.10.1,1.10.1], io.opencensus:opencensus-exporter-stats-stackdriver:jar:0.14.0-SNAPSHOT -> com.google.cloud:google-cloud-monitoring:jar:0.47.0-beta -> io.grpc:grpc-auth:jar:1.10.1 -> io.grpc:grpc-core:jar:[1.10.1,1.10.1]] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Does this project build with this PR on your machine?

**Comment by songy23** [comment]
Oh sorry I forgot to update the gRPC version. Now building should be good.

**Comment by odeke-em** [comment]
No worries, thanks for the update. 

Unfortunately though this doesn't seem to solve the problem, it still crashes with
```shell
Server listening on 9876
[WARNING] 
java.lang.NoSuchFieldError: timestampMs
    at io.prometheus.client.exporter.common.TextFormat.write004 (TextFormat.java:49)
    at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle (HTTPServer.java:59)
    at com.sun.net.httpserver.Filter$Chain.doFilter (Filter.java:77)
    at sun.net.httpserver.AuthFilter.doFilter (AuthFilter.java:82)
    at com.sun.net.httpserver.Filter$Chain.doFilter (Filter.java:80)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle (ServerImpl.java:685)
    at com.sun.net.httpserver.Filter$Chain.doFilter (Filter.java:77)
    at sun.net.httpserver.ServerImpl$Exchange.run (ServerImpl.java:657)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
    at java.lang.Thread.run (Thread.java:844)
[WARNING] 
java.lang.NoSuchFieldError: timestampMs
    at io.prometheus.client.exporter.common.TextFormat.write004 (TextFormat.java:49)
    at io.prometheus.client.exporter.HTTPServer$HTTPMetricHandler.handle (HTTPServer.java:59)
    at com.sun.net.httpserver.Filter$Chain.doFilter (Filter.java:77)
    at sun.net.httpserver.AuthFilter.doFilter (AuthFilter.java:82)
    at com.sun.net.httpserver.Filter$Chain.doFilter (Filter.java:80)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle (ServerImpl.java:685)
    at com.sun.net.httpserver.Filter$Chain.doFilter (Filter.java:77)
    at sun.net.httpserver.ServerImpl$Exchange.run (ServerImpl.java:657)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
```

**Comment by songy23** [comment]
Closing - I'll make a patch release to update the transitive dependencies of OC-Java.

**Pull request closed without merging**
